apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: course
          valueFrom:
            configMapKeyRef:
              name: nginx-config
              key: course
        - name: trainer
          valureFrom:
            configMapKeyRef:
              name: nginx-config
              key: trainer