apiVersion: v1
kind: Service
metadata: 
  name: nginx
spec:
  selector:
    project: expense
    enevironment: dev
    module: backend
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80 #service port
    targetPort: 80 #container port
  