apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  selector:
    type: NodePort
    project: expense
    enevironment: dev
    module: backend
  ports:
  - name: nginx-svc-nodeport
    protocol: TCP
    port: 80
    targetPort: 80