apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    tier: frontend
    app: nginx
spec:    
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
      app: nginx
  template:
   metadata:
    name: nginx
    labels:
      tier: frontend
      app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable-perl
---
kind: Service
apiVersion: v1
spec:
  selector:
    tier: frontend
    app: nginx
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80
    targetPort: 80
  