apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: expense-efs
provisioner: ebs.csi.aws.com 
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0bd850b665cba00d8
  directoryPerms: "700"
  basePath: "/expense" # optional
 